#! /bin/zsh
echo -n "Running this will \e[31moverwrite\e[0m the code that is currently \
on BluePebble. Are you sure you want to continue? ([y]/n) "
read response
if [[ $response != "y" && $response != "" ]]; then
    exit 1
fi

rsync -av --exclude="*.pyc" --exclude=".DS_Store" \
    run run3090 interactive train_jacobian_sae.py jacobian_saes bp:~/jacobian_saes
