#! /bin/sh

for l in {0..6}
do
    ./hpc_utils/train -q mlcnu -w jsaes-scad -s scad -l "$l"
done


for l in {0..23..2}
do
    ./hpc_utils/train --80g --model-preset 410m -w jsaes-scad -s scad -l "$l"
done


for l in {0..15..2}
do
    ./hpc_utils/train --80g --model-preset 1b -w jsaes-scad -s scad -l "$l"
done


for l in {0..31..2}
do
    ./hpc_utils/train --80g --model-preset 6.9b -w jsaes-scad -s scad -l "$l"
done


for l in {1..23..2}
do
    ./hpc_utils/train --80g --model-preset 410m -w jsaes-scad -s scad -l "$l"
done


for l in {1..15..2}
do
    ./hpc_utils/train --80g --model-preset 1b -w jsaes-scad -s scad -l "$l" 
done


for l in {1..31..2}
do
    ./hpc_utils/train --80g --model-preset 6.9b -w jsaes-scad -s scad -l "$l"
done

# ideal model scales: 70m, 410m, 2.8b, 12b
# model scales if I can't fit 12b: 70m, 410m, 1b, 6.9b
