#! /bin/zsh
echo -n "Running this will \e[31moverwrite\e[0m the code that is currently \
on BluePebble. Are you sure you want to continue? ([y]/n) "
read response
if [[ $response != "y" && $response != "" ]]; then
    exit 1
fi

SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
PARENT_DIR=$(dirname "$SCRIPT_DIR")

rsync -av --exclude="*.pyc" --exclude=".DS_Store" \
    "$PARENT_DIR/hpc_utils" "$PARENT_DIR/jacobian_saes" "$PARENT_DIR/runners" \
    bp:~/work/jacobian_saes


