#! /bin/sh
cd ~/work/jacobian_saes

./hpc_utils/train -q mlcnu -w jsae-targets3 -j 0

for s in l1 l1nb l1nt tanh scad log2 exp cl1 cl1nb cl1nt loge lp l4
do
    ./hpc_utils/train -q mlcnu -w jsae-targets3 -s $s
done
