#! /bin/sh
cd ~/work/jacobian_saes
lbatch -c 1 -g 1 -t 12 -m 22 -a COSC020762 -q mlcnu --conda-env base\
    -n jacobian --cmd python ./runners/train_jacobian_sae.py $@

# lbatch -c 1 -g 1 -t 12 -m 22 -a COSC020762 -q gpu --gputype=rtx_3090 --conda-env base\
#     -n jacobian --cmd python ./runners/train_jacobian_sae.py -c 512 $@
