#! /bin/sh
# spreads jobs across queues and nodes in the optimal order
cd ~/work/jacobian_saes
for l in {1..23..2}
do
    ./hpc_utils/train --80g -m 410m -w pythia-410m-v2 -l "$l" -e 64 -j 0.5
    # ./hpc_utils/train --80g --m 410m -w pythia-410m-v2 -l "$l" -e 64 -j 0
done
# for l in {0..23}
# do
#     ./hpc_utils/train --80g --m 410m -w pythia-410m-v2 -l "$l" --eval-batch-size 4 -r
#     ./hpc_utils/train --80g --m 410m -w pythia-410m-v2 -l "$l" --eval-batch-size 4 -j 0 -r
# done

# ./hpc_utils/train --80g --m 410m -w pythia-410m-v2 -l 15 -e 64
# ./hpc_utils/train --80g --m 410m -w pythia-410m-v2 -l 15 -e 64 -j 0
# ./hpc_utils/train --80g --m 410m -w pythia-410m-v2 -l 15 -e 64 -r 
# ./hpc_utils/train --80g --m 410m -w pythia-410m-v2 -l 15 -e 64 -j 0 -r
